# Underwater acoustic propagation modeling with arlpy and Bellhop

The underwater acoustic propagation modeling toolbox (uwapm) in arlpy is integrated with the popular Bellhop ray tracer distributed as part of the acoustics toolbox. In this notebook, we see how to use arlpy.uwapm to simplify the use of Bellhop for modeling.

## Prerequisites
- Install `arlpy` (v1.5 or higher)
- Install the `acoustics toolbox` (6 July 2018 version or later)

## Getting Started
Start with checking that everything is working correctly....
- Docs: https://arlpy.readthedocs.io/en/latest/index.html
- installation guide `(Win 10)`: https://patel999jay.github.io/post/bellhop-acoustic-toolbox/Installation_Manual_draft.pdf

In [7]:
import arlpy.uwapm as pm
import arlpy.plot as plt
import numpy as np

In [8]:
pm.models()

['bellhop']

The bellhop model should be listed in the list of models above, if everything is good. If it isn't listed, it means that bellhop.exe is not available on the PATH, or it cannot be correctly executed.

Ensure that bellhop.exe from the acoustics toolbox installation is on your PATH (updated .profile or equivalent, if necessary, to add it in).

From here on we assume that the `bellhop` model is available, and proceed...

We next create an underwater 2D environment (with default settings) to model:

In [ ]:
pm.create_env2d()

In [9]:
env = pm.create_env2d()
pm.print_env(env)

                name : arlpy
   bottom_absorption : 0.1
      bottom_density : 1600
    bottom_roughness : 0
   bottom_soundspeed : 1600
               depth : 25
        depth_interp : linear
           frequency : 25000
           max_angle : 80
           min_angle : -80
              nbeams : 0
            rx_depth : 10
            rx_range : 1000
          soundspeed : 1500
   soundspeed_interp : spline
             surface : None
      surface_interp : linear
            tx_depth : 5
   tx_directionality : None
                type : 2D

We can see the default values above. Most numbers are in SI units. The only ones that aren't are:

- `bottom_absoption` is in `dB/wavelength`
- `min_angle` and `max_angle` are in `degrees`

The default environment is an isovelocity Pekeris waveguide with a water `depth` of 25 m, an `omnidirectional transmitter` at 5 m depth, and a `receiver` at 10 m depth 1 km away. We can visualize the environment (not to scale):

In [17]:
pm.plot_env(env, width=900)

BokehDeprecationWarning: 'asterisk() method' was deprecated in Bokeh 3.4.0 and will be removed, use "scatter(marker='asterisk', ...) instead" instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.4.0 and will be removed, use 'scatter(size=...) instead' instead.

Let's simulate it and see what the eigenrays between the transmitter and receiver look like:

In [18]:
rays = pm.compute_eigenrays(env)
pm.plot_rays(rays, env=env, width=1000)

BokehDeprecationWarning: 'asterisk() method' was deprecated in Bokeh 3.4.0 and will be removed, use "scatter(marker='asterisk', ...) instead" instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.4.0 and will be removed, use 'scatter(size=...) instead' instead.

We can also compute the arrival structure at the receiver:

In [12]:
arrivals = pm.compute_arrivals(env)
pm.plot_arrivals(arrivals, width=900)

The arrivals are returned in pandas data frame that we can query, if we like. For example, we can look up the time of arrival, angle of arrival, and the number of surface/bottom bounces for the first 10 entries in the arrivals list (not necessarily sorted by time):m

In [14]:
arrivals[arrivals.arrival_number < 10][['time_of_arrival', 'angle_of_arrival', 'surface_bounces', 'bottom_bounces']]

    time_of_arrival  angle_of_arrival  surface_bounces  bottom_bounces
1          0.721796         22.538252                9               8
2          0.716791        -21.553991                8               8
3          0.709687         20.084017                8               7
4          0.709687         20.052010                8               7
5          0.705226        -19.034414                7               7
6          0.698960         17.484421                7               6
7          0.695070        -16.436060                6               6
8          0.689678         14.842224                6               5
9          0.686383        -13.766296                5               5
10         0.681901         12.133879                5               4

In [15]:
import pandas as pd

arrivals.head()

,tx_depth_ndx,rx_depth_ndx,rx_range_ndx,tx_depth,rx_depth,rx_range,arrival_number,arrival_amplitude,time_of_arrival,complex_time_of_arrival,angle_of_departure,angle_of_arrival,surface_bounces,bottom_bounces
1,0,0,0,5.0,10.0,1000.0,0,-5.345778e-06-2.367754e- 06j,0.721796,0.721796-0.000005j,-22.538252,22.538252,9,8
2,0,0,0,5.0,10.0,1000.0,1,7.827161e-06+1.457859e- 05j,0.716791,0.716791-0.000005j,-21.553991,-21.553991,8,8
3,0,0,0,5.0,10.0,1000.0,2,-4.552358e-07-2.436653e- 07j,0.709687,0.709687-0.000005j,-20.084017,20.084017,8,7
4,0,0,0,5.0,10.0,1000.0,3,-2.161610e-04-9.366950e- 05j,0.709687,0.709687-0.000005j,-20.052010,20.052010,8,7
5,0,0,0,5.0,10.0,1000.0,4,-1.553080e-04+2.801340e- 04j,0.705226,0.705226-0.000005j,-19.034414,-19.034414,7,7